# .github/workflows/ci.yml

name: CI Pipeline for MERN Stack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    env:
      MONGO_URI: mongodb://localhost:27017/testdb
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache Backend Dependencies
        uses: actions/cache@v2
        with:
          path: server/node_modules
          key: ${{ runner.os }}-server-${{ hashFiles('**/server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-server-

      - name: Install and Test Backend
        working-directory: ./server
        run: |
          npm install
          npm test

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cache Frontend Dependencies
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-client-${{ hashFiles('**/client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-client-

      - name: Install and Test Frontend
        working-directory: ./client
        run: |
          npm install
          npm test

      - name: Build Frontend
        working-directory: ./client
        run: npm run build

  deploy:
    needs: [backend-tests, frontend-tests]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Deploy Application
        run: echo "Deploying application..." # Replace with actual deploy steps
