# .github/workflows/ci.yml

name: CI Pipeline for MERN Stack

# Trigger the workflow on push and pull request to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      # MongoDB service for backend testing
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    env:
      MONGO_URI: mongodb://localhost:27017/testdb

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Use the Node version compatible with your project

      # Step 3: Install and Test Backend (Node/Express API)
      - name: Install and Test Backend
        working-directory: ./server
        run: |
          npm install
          npm test  # Replace with `npm run test` if that's the command

      # Step 4: Install and Test Frontend (React App)
      - name: Install and Test Frontend
        working-directory: ./client
        run: |
          npm install
          npm test  # Replace with `npm run test` if that's the command

      # Optionally add a build step for the frontend if required
      - name: Build Frontend
        working-directory: ./client
        run: |
          npm run build
